################################################################################
#
# Notes on how to bootstrap first run:
#
# * Create admin user:
# wdaemanage.py user_create admin@iossifovlab.com -p secret -g any_dataset:admin
#
# * Create dev apps:
# cd /gpf/lib/python3.9/site-packages/wdae
# wdaemanage.py shell < create_dev_apps.py
#
################################################################################


version: '2.1'
services:
  mysqldata:
      image: busybox:latest
      command: echo "mysql data only container"

  mysql:
      image: mysql:5.7.36
      hostname: mysql
      environment:
        - MYSQL_DATABASE=gpf
        - MYSQL_USER=seqpipe
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=secret
      volumes_from:
        - mysqldata
      networks:
        main:
          aliases:
            - mysql
      ports:
        - "3306:3306"
      command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin', ]

  gpf:
      image: registry.seqpipe.org/iossifovlab-gpf-full:latest
      hostname: gpf
      networks:
        main:
          aliases:
            - gpf
      volumes:
      - ${DAE_DB_DIR:?DAE_DB_DIR is not defined}:/data
      - ${DAE_PHENODB_DIR:?DAE_PHENODB_DIR is not defined}:/data-phenodb
      - ${GRR_CACHE:?GRR_CACHE is not defined}:/cache
      environment:
      - DAE_DB_DIR=/data
      - DAE_PHENODB_DIR=/data-phenodb
      - WDAE_DB_NAME=gpf
      - WDAE_DB_USER=seqpipe
      - WDAE_DB_PASSWORD=secret
      - WDAE_DB_HOST=mysql
      - WDAE_DB_PORT=3306
      - WDAE_SECRET_KEY="123456789012345678901234567890123456789012345678901234567890"
      - WDAE_ALLOWED_HOST=*
      - WDAE_DEBUG=True
      - WDAE_PUBLIC_HOSTNAME=gpf
      - WDAE_LOG_DIR=/logs
      - GPF_PREFIX=gpf_prefix
      - WDAE_PREFIX=gpf_prefix
      - GRR_DEFINITION_FILE=/cache/grr_definition.yaml
      - IMPALA_HOSTS=seqclust0 seqclust1 seqclust2
      - DOCKER_COMPOSE_CORS_WORKAROUND=True

  frontpage:
      image: registry.seqpipe.org/iossifovlab-sfari-frontpage:latest
      hostname: frontpage
      networks:
        main:
          aliases:
            - frontpage
      environment:
      - GPF_FRONTPAGE_INSTANCE_PREFIX=frontpage_prefix
      - GPF_OAUTH_ENDPOINT=localhost:9000
      - GPF_OAUTH_PREFIX=gpf_prefix
      - GPF_INSTANCES_1_ENDPOINT=localhost:9000
      - GPF_INSTANCES_1_PREFIX=gpf_prefix
      - GPF_INSTANCES_1_API_PATH=/api/v3/
      - GPF_INSTANCES_1_FRONTEND_PATH=/

  proxy:
      image: registry.seqpipe.org/iossifovlab-gpf-fronting-proxy:latest
      hostname: proxy
      ports:
      - "9000:80"
      networks:
        main:
          aliases:
            - proxy
      environment:
       - GPF_FRONTPAGE_INSTANCE_ENDPOINT=frontpage:80
       - GPF_FRONTPAGE_INSTANCE_PREFIX=frontpage_prefix
       - GPF_INSTANCES_1_ENDPOINT=gpf:80
       - GPF_INSTANCES_1_PREFIX=gpf_prefix


networks:
  main:
